language: node_js
node_js:
- '16.18.1'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # REGISTRY_TOKEN slug=directenergie editor=cozy space=cozy_ccc
  - secure: oP/FeCNt+ErpHPgwlcR8h/4zP747pGIsFT3+i0uXOhh7pkiLgOr16rRDnGARyEEsySoNt7rwVE70TFsBX1e1GQqQbxQPfzwgWlUxe9RXZshvH8hyX7LyNeVh6HFQ4G5mJoqBPfd3rsFaErUH50paZP/nUUVlR9JPKJPh8EEXXZO+g1H9GwEPOpBUV4Eohxxque9xLpU3pN/eq2tzQ0XnwK95/0YJKFLaZTpg5PcHTgidB2IHtPfhc/61MlgqxYu6BmBiM8bqSnPu+CZ9c8WMlFlZuZu6N9dsWQyXl/X7RW/5gvOf8gVfBvVysY33AO0pWvZg4SKmPn8+awSn1yLiSKwM978Bd4Ej+opZ3Zm8kpuTIlXnip+FVCblqxGG42RfA0ChMbqqVH2x4xKefk9ivEaMdJ4uW53czLCW1vpp9lsUMw2aH59dPRHuWUbuywIvgUs71DG0mjAUfC1ePAYB9pkAF1bM6wAw5jO3kR/dynnK42fAhWIcQiYD9sv/4BBz7BxmqW3aA7ByqJgcBb5gtTxzA9ky21cIskhi0yDtZzIY0xMolTO4JC4fdG6Ma5pTqwz+vMrPQG65m+60CrOLV9+2bKfhB4Od7Uk7ITocBRxo4fhfLfqafxgazJ0e9PxlkZYoPbqY92oZovHe0hp7fBLKz45IIdw1TQdQF4N91W4=
  # MATTERMOST_HOOK_URL
  - secure: J4TtG1v9ngldA3hos5hU+Fb3SblsGwpP/FLHytZ2Ifv4/VYM1q1loKAm+lsV7l7vFceK6wlCeaQ/voFqDmLzXE2Zotlwh1CkqY6nv4iVJK6NaA4qwX+1sGd4ASdRCF3xUE6TcTXa5MDRahPlg8Ng3A+yXiqz/aMZVYMOEqOuUnI/MJIOViv59ASB988BN5Ze0jK9pS3J9pdpqgiALzDyhG8RTZNSk52y2jIYD5z5uipzPguOBeALtOVHxebFc0heyXBCuWe3QyDrRpK8vrhpM5Gw05PEJoPjxZAju/urR0QU9HmMGGsaYfsprcHThHca8dshC3ysohLRSL1nQxiMrJlabnbbiHxhzNR1P7/tx0vnbtGLVbkBPtZoa7pPmS7djj19X1cEUgOv+ahnAVdBSM+J0r4dMYMu7oCdE8BfvKd6mU+84sJ6aNRZTMbsJEapS2//jaGp4QVGHMaCFE6Lqua/s2sncptvkV49blRzZ1SNW4ggpLknJmxzsc6XhjiETHsudliExAaycifSbQbMXaPBMQaJPwdLCdefeQqLHb0CxDdFQU9OwgX+H4GbcfEiM7W53PncXKIEKEN+TdTQkNaBZYa+/g1m6BPUJBDodqkM8RIOvXw/iFJb+5rMzArPj0IU+s6gD+qM0hOPvfaMbcqwecB8Kn4KS90JCoQ8VSM=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --space cozy_ccc
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost --space cozy_ccc
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
