language: node_js
node_js:
- '16.18.1'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # REGISTRY_TOKEN(editor=cozy, app=directenergie)
  - secure: Z28GOvFbP0p75WJ+aTdUsw1hf1ZGnwns8nRL1X3lR1n4O09fBz707vUJVVVqr/jlh0TBFzXh1yvYbJcfqt1oibq0yw8+7hBYJUYEdz0BS6Kq8ahlNTiGXnIBbig2ARYkKK4JqQmtu8c064R5XYPUu2SgJxCe3DIPDtcXU1TQ/48KpEPqf1RakOlrjACqNi2JXpaJ+GlLuOPPCm5GYBEDA4FUVIkCHXZ05Niv7joXQ6NdhzWFnZVj8O2fd0Eipha2dM5NdJMbq/gmML1vHC+ofaImeMoHtmUsX0PnR8uhjdka5K/boSFJdnkTb3iW9qJUGGyTNRqak8KvkVaWJY+wv6vR2JUwuwKicUT8tBRE5drtrtacVFb5DD9CzBX1BUylfWhvFpG8i0YlA7nbh74PI67VypY5S9An5I7is+VrUJ35v4HY8h3I30DJfLgB3YRRCqhaxanmxO3/MBSJ+1F9U8RmJeC3MNSgeMboiRPSmeEgffgM0PF9uJg4J9FCwZME4X+eIhF2UxOxzUAgSmSRIpxZlz5zkMEMusYnQpHMTwUP0mmmVX6RzaJRT9IWPbHKA2q7k1kGSllWNE9N8UEe+il4olalrCm4P50+Rd3cZNR7HkpNlYGMK3NXUi5ROQJO12rQFvlVv8lmwbeYvajW1beGz9xmahH2MWIoSlNlHCE=
  # MATTERMOST_HOOK_URL
  - secure: J4TtG1v9ngldA3hos5hU+Fb3SblsGwpP/FLHytZ2Ifv4/VYM1q1loKAm+lsV7l7vFceK6wlCeaQ/voFqDmLzXE2Zotlwh1CkqY6nv4iVJK6NaA4qwX+1sGd4ASdRCF3xUE6TcTXa5MDRahPlg8Ng3A+yXiqz/aMZVYMOEqOuUnI/MJIOViv59ASB988BN5Ze0jK9pS3J9pdpqgiALzDyhG8RTZNSk52y2jIYD5z5uipzPguOBeALtOVHxebFc0heyXBCuWe3QyDrRpK8vrhpM5Gw05PEJoPjxZAju/urR0QU9HmMGGsaYfsprcHThHca8dshC3ysohLRSL1nQxiMrJlabnbbiHxhzNR1P7/tx0vnbtGLVbkBPtZoa7pPmS7djj19X1cEUgOv+ahnAVdBSM+J0r4dMYMu7oCdE8BfvKd6mU+84sJ6aNRZTMbsJEapS2//jaGp4QVGHMaCFE6Lqua/s2sncptvkV49blRzZ1SNW4ggpLknJmxzsc6XhjiETHsudliExAaycifSbQbMXaPBMQaJPwdLCdefeQqLHb0CxDdFQU9OwgX+H4GbcfEiM7W53PncXKIEKEN+TdTQkNaBZYa+/g1m6BPUJBDodqkM8RIOvXw/iFJb+5rMzArPj0IU+s6gD+qM0hOPvfaMbcqwecB8Kn4KS90JCoQ8VSM=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
